# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-12-15 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='alamt',
            new_name='alamat',
        ),
    ]
